--EJERCICIO 1
SELECT D.NOMBRE "DEPARTAMENTO",COUNT(ID) "NUMERO PROFESORES" FROM DEPARTAMENTOS D 
JOIN PROFESORES P ON D.CODIGO=P.DEPARTAMENTO
GROUP BY D.NOMBRE
ORDER BY DEPARTAMENTO,D.NOMBRE;

--EJERCICIO 2
SELECT D.NOMBRE "DEPARTAMENTO", SUM(CREDITOS) FROM DEPARTAMENTOS D
JOIN ASIGNATURAS ON DEPARTAMENTO=D.CODIGO
GROUP BY D.NOMBRE,DEPARTAMENTO;

--EJERCICIO 3
SELECT ASIG.CURSO,COUNT(DISTINCT AL.DNI) "NUMERO ALUMNOS"FROM ALUMNOS AL JOIN MATRICULAR M ON M.ALUMNO=AL.DNI
JOIN ASIGNATURAS ASIG ON M.ASIGNATURA=ASIG.CODIGO
GROUP BY ASIG.CURSO
HAVING ASIG.CURSO IS NOT NULL;

--EJERCICIO 4
SELECT DESPACHO, SUM(CARGA_CREDITOS)"TOTAL CREDITOS" FROM PROFESORES JOIN IMPARTIR ON PROFESOR=ID
GROUP BY DESPACHO
HAVING DESPACHO IS NOT NULL;

--EJERCICIO 5
SELECT ASIGNATURA,(SUM(DECODE(GENERO,'MASC',0,'FEM',100))/COUNT(DNI))
FROM MATRICULAR M JOIN ALUMNOS A ON M.ALUMNO=A.DNI
GROUP BY ASIGNATURA
ORDER BY ASIGNATURA;

--EJERCICIO 6
SELECT P.NOMBRE,SUM(HOMBRES)+SUM(MUJERES) "SUMA" FROM PROVINCIA P 
JOIN MUNICIPIO M ON P.CODIGO=M.CPRO
GROUP BY P.NOMBRE
ORDER BY P.NOMBRE;

--EJERCICIO 7
SELECT D.NOMBRE "DEPARTAMENTO",P.NOMBRE||' '||P.APELLIDO1 "PROFESOR"
FROM PROFESORES P JOIN DEPARTAMENTOS D ON P.DEPARTAMENTO=D.CODIGO
WHERE (P.DEPARTAMENTO,P.FECHA_NACIMIENTO)IN(SELECT CODIGO,MIN(FECHA_NACIMIENTO) 
FROM PROFESORES P JOIN DEPARTAMENTOS D ON P.DEPARTAMENTO=D.CODIGO
GROUP BY CODIGO);

--EJERCICIO 8
SELECT DISTINCT A.NOMBRE||' '||A.APELLIDO1||' '||A.APELLIDO2 "ALUMNO", ASI.NOMBRE "ASIGNATURA"
FROM ALUMNOS A JOIN MATRICULAR M ON DNI=M.ALUMNO
JOIN ASIGNATURAS ASI ON M.ASIGNATURA=ASI.CODIGO
WHERE (DNI,CREDITOS) IN (SELECT ALUMNO,MAX(CREDITOS) FROM MATRICULAR M JOIN ASIGNATURAS ASI ON M.ASIGNATURA=ASI.CODIGO
GROUP BY ALUMNO);

--EJERCICIO 9
SELECT D.NOMBRE "DEPARTAMENTOS",  P.NOMBRE||' '||P.APELLIDO1 "PROFESOR"
FROM DEPARTAMENTOS D JOIN PROFESORES P ON D.CODIGO=P.DEPARTAMENTO
WHERE (D.CODIGO, P.ANTIGUEDAD) IN (SELECT DEPARTAMENTO, MIN(ANTIGUEDAD) FROM PROFESORES 
GROUP BY DEPARTAMENTO);

--EJERCICIO 10
SELECT D.NOMBRE "DEPARTAMENTO", A.NOMBRE "ASIGNATURA" FROM DEPARTAMENTOS D JOIN ASIGNATURAS A ON A.DEPARTAMENTO=D.CODIGO
WHERE (D.CODIGO,A.CREDITOS) IN (SELECT DEPARTAMENTO,MIN(CREDITOS) FROM ASIGNATURAS 
GROUP BY DEPARTAMENTO);

--EJERCICIO 11
SELECT ASI.NOMBRE, (A.NOMBRE||' '||A.APELLIDO1||' '||A.APELLIDO2) ALUMNO, A.FECHA_NACIMIENTO "FECHA DE NACIMIENTO"
FROM ALUMNOS A JOIN MATRICULAR M ON (A.DNI = M.ALUMNO) JOIN ASIGNATURAS ASI ON(ASI.CODIGO = M.ASIGNATURA)
WHERE M.CURSO = '14/15' AND (M.ASIGNATURA, A.FECHA_NACIMIENTO) IN
(SELECT M.ASIGNATURA, MAX(A.FECHA_NACIMIENTO)
FROM ALUMNOS A JOIN MATRICULAR M ON (A.DNI = M.ALUMNO) JOIN ASIGNATURAS ASI ON(ASI.CODIGO = M.ASIGNATURA)
WHERE ASI.CODIGO=M.ASIGNATURA AND M.CURSO='14/15'
GROUP BY M.ASIGNATURA)
ORDER BY ASI.NOMBRE;

--EJERCICIO 12
SELECT P.NOMBRE || ' ' || P.APELLIDO1 "PROFESOR", SUM(NVL(I.CARGA_CREDITOS,0))"CREDITOS"
FROM IMPARTIR I JOIN PROFESORES P ON (I.PROFESOR=P.ID)
GROUP BY I.PROFESOR, P.NOMBRE, P.APELLIDO1
HAVING SUM(NVL(I.CARGA_CREDITOS,0))=(SELECT MAX(SUM(NVL(CARGA_CREDITOS,0)))
FROM IMPARTIR
GROUP BY PROFESOR);

--EJERCICIO 13
SELECT D.NOMBRE "DEPARTAMENTO" FROM DEPARTAMENTOS D
WHERE(SELECT COUNT(*) FROM ASIGNATURAS A
      WHERE A.DEPARTAMENTO = D.CODIGO)=
      (SELECT MAX(COUNT(*))FROM ASIGNATURAS
      GROUP BY DEPARTAMENTO);

--EJRCICIO 14
SELECT PROFESOR,SUM(CARGA_CREDITOS) "CREDITOS" FROM IMPARTIR
GROUP BY PROFESOR
HAVING SUM(CARGA_CREDITOS)<10;

--EJERCICIO 15
SELECT P.NOMBRE,P.APELLIDO1,P.APELLIDO2 FROM PROFESORES P
JOIN IMPARTIR I ON I.PROFESOR = P.ID
GROUP BY P.NOMBRE , P.APELLIDO1 ,P.APELLIDO2
HAVING SUM(CARGA_CREDITOS) > (SELECT AVG(SUM(CARGA_CREDITOS)) FROM IMPARTIR
GROUP BY PROFESOR);


--EJERCICIO 16
SELECT  PROFESOR FROM IMPARTIR JOIN PROFESORES ON PROFESOR=ID
WHERE CURSO='15/16' AND CARGA_CREDITOS <6.5
GROUP BY PROFESOR
HAVING COUNT (ASIGNATURA)>=2;

--EJERCICIO 17
SELECT NOMBRE FROM ASIGNATURAS 
WHERE (CODIGO) NOT IN (SELECT CODIGO FROM ASIGNATURAS JOIN MATRICULAR ON CODIGO=ASIGNATURA
WHERE CALIFICACION!='SP');

--EJERCICIO 18
SELECT NOMBRE FROM DEPARTAMENTOS
WHERE (CODIGO) NOT IN (SELECT D.CODIGO FROM DEPARTAMENTOS D JOIN ASIGNATURAS A ON A.DEPARTAMENTO=D.CODIGO
WHERE CREDITOS >6);

--EJERCICIO 19
SELECT DISTINCT P.NOMBRE, P.APELLIDO1, P.APELLIDO2
FROM PROFESORES P JOIN IMPARTIR I ON P.ID = I.PROFESOR JOIN ASIGNATURAS A ON I.ASIGNATURA = A.CODIGO
WHERE A.CARACTER = 'OP' AND (ID) NOT IN (SELECT I.PROFESOR
FROM MATRICULAR M NATURAL JOIN IMPARTIR I);

--EJERCICIO 20
SELECT * FROM SOL_3_20
MINUS
SELECT P1.NOMBRE||' '||P1.APELLIDO1||' '||P1.APELLIDO2 PROFESOR1, 
P2.NOMBRE||' '||P2.APELLIDO1||' '||P2.APELLIDO2 PROFESOR2
FROM PROFESORES P1, PROFESORES P2	WHERE P1.ID<P2.ID
AND NOT EXISTS(SELECT M.ALUMNO FROM MATRICULAR M NATURAL JOIN IMPARTIR I
WHERE P1.ID=I.PROFESOR
INTERSECT
SELECT M.ALUMNO	FROM MATRICULAR M NATURAL JOIN IMPARTIR I
WHERE P2.ID=I.PROFESOR)
;
    
--EJERCICIO 21
SELECT P1.NOMBRE||' '||P1.APELLIDO1||' '||P1.APELLIDO2 PROFESOR1,
P2.NOMBRE||' '||P2.APELLIDO1||' '||P2.APELLIDO2 PROFESOR2
FROM PROFESORES P1, PROFESORES P2 
WHERE P1.ID<P2.ID AND NOT EXISTS(SELECT I.ASIGNATURA FROM IMPARTIR I
WHERE P1.ID=I.PROFESOR
INTERSECT
SELECT I.ASIGNATURA FROM IMPARTIR I
WHERE P2.ID=I.PROFESOR);

--EJERCICIO 22
SELECT NOMBRE FROM ASIGNATURAS WHERE (CODIGO) NOT IN
(SELECT DISTINCT M.ASIGNATURA FROM ALUMNOS A JOIN MATRICULAR M ON DNI=ALUMNO JOIN MUNICIPIO MU ON A.CMUN=MU.CMUN
GROUP BY A.CMUN,M.ASIGNATURA
HAVING COUNT(DISTINCT ALUMNO)>2);

--EJERCICIO 23
SELECT DISTINCT ALUMNO FROM MATRICULAR NATURAL JOIN IMPARTIR
WHERE PROFESOR NOT IN (SELECT ID FROM PROFESORES
WHERE FECHA_NACIMIENTO=(SELECT MIN(FECHA_NACIMIENTO) FROM PROFESORES));

--EJERCICIO 24 
SELECT DISTINCT ALUMNO FROM MATRICULAR M JOIN ASIGNATURAS ASI ON M.ASIGNATURA=ASI.CODIGO JOIN IMPARTIR I ON I.ASIGNATURA=ASI.CODIGO WHERE 
ALUMNO IN (SELECT DISTINCT ALUMNO FROM ASIGNATURAS ASI JOIN MATRICULAR M ON M.ASIGNATURA=ASI.CODIGO GROUP BY ALUMNO HAVING COUNT(*)>2)
AND I.PROFESOR NOT IN (SELECT DISTINCT ID FROM PROFESORES P JOIN DEPARTAMENTOS D ON DEPARTAMENTO=CODIGO WHERE UPPER(D.NOMBRE)='MATEMATICA APLICADA');

--EJERCICIO 25 
SELECT DISTINCT CODIGO, DEPARTAMENTO FROM ASIGNATURAS
WHERE (CODIGO) IN (SELECT CODIGO FROM ASIGNATURAS 
WHERE(CREDITOS,DEPARTAMENTO) IN (SELECT MAX(NVL(CREDITOS,0)),DEPARTAMENTO FROM ASIGNATURAS JOIN IMPARTIR ON ASIGNATURA=CODIGO
WHERE PROFESOR NOT IN
(SELECT ID FROM PROFESORES WHERE NVL(TO_CHAR(FECHA_NACIMIENTO,'YYYY'),0)<1970)
GROUP BY DEPARTAMENTO));

--EJERCICO 27 
SELECT PROFESOR, COUNT(ALUMNO) FROM IMPARTIR I  JOIN ASIGNATURAS ASI ON I.ASIGNATURA=ASI.CODIGO
JOIN MATRICULAR M ON ASI.CODIGO=M.ASIGNATURA WHERE M.ASIGNATURA IN
(SELECT CODIGO FROM ASIGNATURAS WHERE NVL(PRACTICOS,0)>NVL(TEORICOS,0))
GROUP BY PROFESOR;


--EJERCICIO 28

SELECT A.DEPARTAMENTO,D.NOMBRE FROM ASIGNATURAS A JOIN DEPARTAMENTOS D ON A.DEPARTAMENTO=D.CODIGO
GROUP BY DEPARTAMENTO,D.NOMBRE
HAVING SUM(CREDITOS)= (SELECT MAX(SUM(CREDITOS)) FROM ASIGNATURAS
GROUP BY DEPARTAMENTO);