--EJERCICIO 1
SELECT P.NOMBRE, APELLIDO1,APELLIDO2 FROM PROFESORES P JOIN DEPARTAMENTOS D ON P.DEPARTAMENTO=D.CODIGO WHERE D.NOMBRE LIKE '%Lenguajes%';

--EJERCICIO 2
SELECT A.CODIGO "ASIGNATURA",A.NOMBRE,NVL(TO_CHAR(PRACTICOS),'No tiene') "CREDITOS PRACTICOS" FROM ASIGNATURAS A 
JOIN MATRICULAR M ON M.ASIGNATURA=A.CODIGO JOIN ALUMNOS AL ON AL.DNI=M.ALUMNO 
WHERE AL.NOMBRE ='Nicolas' AND AL.APELLIDO1='Bersabe' AND AL.APELLIDO2='Alba';

--EJERCICIO 3)
SELECT P.NOMBRE,APELLIDO1,APELLIDO2, TRUNC((SYSDATE-ANTIGUEDAD)/7) "ANTIGUEDAD",NEXT_DAY(SYSDATE-1,TO_CHAR(ANTIGUEDAD,'DAY')) "SE CUMPLE UNA SEMANA" FROM PROFESORES P 
JOIN DEPARTAMENTOS D ON P.DEPARTAMENTO=D.CODIGO WHERE D.NOMBRE='Ingenieria de Comunicaciones';

--EJERCICIO 4
SELECT * FROM ALUMNOS AL
JOIN MATRICULAR M ON AL.DNI=M.ALUMNO JOIN ASIGNATURAS A ON M.ASIGNATURA=A.CODIGO  
WHERE M.CALIFICACION IN ('AP','NT','SB','MT') AND A.NOMBRE='Bases de Datos';

--EJERCICIO 5
SELECT ID,P.NOMBRE,APELLIDO1,APELLIDO2,A.CODIGO,A.NOMBRE "ASIGNATURA" FROM PROFESORES P JOIN DEPARTAMENTOS D ON P.DEPARTAMENTO=D.CODIGO 
JOIN ASIGNATURAS A ON A.DEPARTAMENTO=D.CODIGO;

--EJERCICIO 6
SELECT A1.NOMBRE "Nombre 1",TRUNC(MONTHS_BETWEEN(SYSDATE,A1.FECHA_NACIMIENTO)/12) "Edad 1",A2.NOMBRE "Nombre 2",TRUNC(MONTHS_BETWEEN(SYSDATE,A2.FECHA_NACIMIENTO)/12) "Edad 2"
FROM ALUMNOS A1, ALUMNOS A2
WHERE A1.APELLIDO1=A2.APELLIDO1 AND A1.DNI<A2.DNI;

--EJERCICIO 7
SELECT A1.APELLIDO1 "PRIMER APELLIDO",A2.APELLIDO1 "SEGUNDO APELLIDO" FROM ALUMNOS A1, ALUMNOS A2
WHERE TO_CHAR(A1.FECHA_NACIMIENTO,'YYYY') BETWEEN 1995 AND 1996 
AND
TO_CHAR(A2.FECHA_NACIMIENTO,'YYYY') BETWEEN 1995 AND 1996
AND
A1.DNI<A2.DNI;

--EJERCICIO 8
SELECT DISTINCT P1.NOMBRE "NOMBREP1",P1.APELLIDO1 "APELLIDO1P1",P1.APELLIDO2 "APELLIDO2P1",
TRUNC(MONTHS_BETWEEN(SYSDATE,P1.ANTIGUEDAD)/12) "ANTIGUEDAD 1",
P2.NOMBRE "NOMBREP2",P2.APELLIDO1 "APELLIDO1P2",P2.APELLIDO2 "APELLIDO2P2",
TRUNC(MONTHS_BETWEEN(SYSDATE,P2.ANTIGUEDAD)/12) "ANTIGUEDAD 2"
FROM PROFESORES P1, PROFESORES P2
WHERE ABS((MONTHS_BETWEEN(SYSDATE,P1.ANTIGUEDAD)/12)-(MONTHS_BETWEEN(SYSDATE,P2.ANTIGUEDAD)/12))<=2
AND
P1.DEPARTAMENTO=P2.DEPARTAMENTO AND P1.ID!=P2.ID AND P1.ID<P2.ID;

--EJERCICIO 9
SELECT DISTINCT A1.NOMBRE||' '||A1.APELLIDO1||' '||A1.APELLIDO2 "ELLA", A2.NOMBRE||' '||A2.APELLIDO1||' '||A2.APELLIDO2 "EL"
FROM ALUMNOS A1 JOIN MATRICULAR M1 ON A1.DNI=M1.ALUMNO, ALUMNOS A2 JOIN MATRICULAR M2 ON A2.DNI=M2.ALUMNO
WHERE A1.GENERO='FEM' AND A2.GENERO='MASC' AND M1.ASIGNATURA='112' AND M2.ASIGNATURA='112'
AND TO_CHAR(A1.FECHA_PRIM_MATRICULA,'MM')=TO_CHAR(A2.FECHA_PRIM_MATRICULA,'MM') 
AND ABS(TO_CHAR(A1.FECHA_PRIM_MATRICULA,'DD')-TO_CHAR(A2.FECHA_PRIM_MATRICULA,'DD'))<=7
AND DECODE(M1.CALIFICACION,NULL,0,'SP',1,'AP',2,'NT',3,'SB',4,'MH',5)>DECODE(M2.CALIFICACION,NULL,0,'SP',1,'AP',2,'NT',3,'SB',4,'MH',5);

--EJERCICO 10
SELECT A1.NOMBRE "Asignatura 1",A2.NOMBRE "Asignatura 2",A3.NOMBRE "Asignatura 3", A1.COD_MATERIA "Materia"
FROM ASIGNATURAS A1, ASIGNATURAS A2, ASIGNATURAS A3
WHERE A1.COD_MATERIA=A2.COD_MATERIA AND A2.COD_MATERIA=A3.COD_MATERIA
AND A1.NOMBRE<A2.NOMBRE AND A2.NOMBRE<A3.NOMBRE AND A1.NOMBRE<A3.NOMBRE;

--EJERCICIO 11
SELECT A.NOMBRE,APELLIDO1,APELLIDO2,ASI.NOMBRE "ASIGNATURA",DECODE(M.CALIFICACION,NULL,'No Presentado','SP','Suspenso','AP','Aprobado','NT','Notable','SB','Sobresaliente','MH','Matricula de Honor') "NOTAS" FROM ALUMNOS A 
JOIN MATRICULAR M ON A.DNI=M.ALUMNO JOIN ASIGNATURAS ASI ON M.ASIGNATURA=ASI.CODIGO
WHERE TRUNC(MONTHS_BETWEEN(SYSDATE,A.FECHA_NACIMIENTO)/12)>=22
ORDER BY APELLIDO1,APELLIDO2,A.NOMBRE;

--EJERCICIO 12
SELECT DISTINCT A.NOMBRE, A.APELLIDO1,A.APELLIDO2 FROM ALUMNOS A JOIN MATRICULAR M ON A.DNI=M.ALUMNO 
JOIN ASIGNATURAS ASI ON M.ASIGNATURA=ASI.CODIGO JOIN IMPARTIR I ON ASI.CODIGO=I.ASIGNATURA AND I.GRUPO=M.GRUPO AND I.CURSO=M.CURSO
JOIN PROFESORES P ON I.PROFESOR=P.ID
WHERE (P.NOMBRE||' '||P.APELLIDO1||' '||P.APELLIDO2) LIKE 'Enrique Soler%' 
ORDER BY APELLIDO1,APELLIDO2,A.NOMBRE;

--EJERCICIO 13
SELECT DISTINCT A.NOMBRE, A.APELLIDO1,A.APELLIDO2 FROM ALUMNOS A JOIN MATRICULAR M ON A.DNI=M.ALUMNO 
JOIN ASIGNATURAS ASI ON M.ASIGNATURA=ASI.CODIGO JOIN IMPARTIR I ON ASI.CODIGO=I.ASIGNATURA AND I.GRUPO=M.GRUPO AND I.CURSO=M.CURSO
JOIN PROFESORES P ON I.PROFESOR=P.ID JOIN DEPARTAMENTOS D ON P.DEPARTAMENTO=D.CODIGO
WHERE D.NOMBRE = 'Lenguajes y Ciencias de la Computacion'
ORDER BY APELLIDO1,APELLIDO2,A.NOMBRE;

--EJERCICIO 14
SELECT ASI.NOMBRE "Asignatura", M.NOMBRE "Materia", P.NOMBRE||' '||P.APELLIDO1||' '||P.APELLIDO2 "Profesor", I.CARGA_CREDITOS
FROM ASIGNATURAS ASI JOIN MATERIAS M ON ASI.COD_MATERIA=M.CODIGO
JOIN IMPARTIR I ON I.ASIGNATURA=ASI.CODIGO JOIN PROFESORES P ON I.PROFESOR=P.ID
WHERE I.CARGA_CREDITOS IS NOT NULL
ORDER BY M.CODIGO, ASI.NOMBRE DESC;

--EJERCICIO 15
SELECT ASI.NOMBRE "Asignatura", D.NOMBRE "Departamento", ASI.CREDITOS,ROUND(((ASI.PRACTICOS/(ASI.CREDITOS))*100),2) "Practicos (%)"
FROM ASIGNATURAS ASI JOIN DEPARTAMENTOS D ON ASI.DEPARTAMENTO=D.CODIGO
WHERE ASI.CREDITOS IS NOT NULL AND ASI.PRACTICOS IS NOT NULL AND ASI.PRACTICOS IS NOT NULL
ORDER BY ROUND(((ASI.PRACTICOS/(ASI.CREDITOS))*100),2) DESC;

--EJERCICIO 16
SELECT DISTINCT CODIGO FROM ASIGNATURAS
MINUS
SELECT DISTINCT ASI.CODIGO FROM ASIGNATURAS ASI JOIN IMPARTIR I ON I.ASIGNATURA=ASI.CODIGO 
JOIN PROFESORES P ON I.PROFESOR=P.ID;

--EJERCICIO 17
SELECT EMAIL FROM PROFESORES WHERE EMAIL IS NOT NULL
UNION ALL
SELECT EMAIL FROM ALUMNOS WHERE EMAIL IS NOT NULL;

--EJERCICIO 18
SELECT AL.APELLIDO1 "APELLIDO" FROM ALUMNOS AL, PROFESORES PR WHERE LOWER(AL.APELLIDO1)=LOWER(PR.APELLIDO1) OR LOWER(AL.APELLIDO1)=LOWER(PR.APELLIDO2)
UNION
SELECT AL.APELLIDO2 "APELLIDO" FROM ALUMNOS AL, PROFESORES PR WHERE LOWER(AL.APELLIDO2)=LOWER(PR.APELLIDO1) OR LOWER(AL.APELLIDO2)=LOWER(PR.APELLIDO2)
INTERSECT
SELECT PR.APELLIDO1 "APELLIDO" FROM ALUMNOS AL, PROFESORES PR WHERE LOWER(PR.APELLIDO1)=LOWER(AL.APELLIDO1) OR LOWER(PR.APELLIDO1)=LOWER(AL.APELLIDO2)
UNION
SELECT PR.APELLIDO2 "APELLIDO" FROM ALUMNOS AL, PROFESORES PR WHERE LOWER(PR.APELLIDO2)=LOWER(AL.APELLIDO1) OR LOWER(PR.APELLIDO2)=LOWER(AL.APELLIDO2);

--EJERCICIO 19
SELECT DISTINCT APELLIDO1 "APELLIDOS" FROM ALUMNOS WHERE UPPER(APELLIDO1) LIKE '%LL%'
UNION
SELECT DISTINCT APELLIDO2 "APELLIDOS" FROM ALUMNOS WHERE UPPER(APELLIDO2) LIKE '%LL%'
UNION
SELECT DISTINCT APELLIDO1 "APELLIDOS" FROM PROFESORES WHERE UPPER(APELLIDO1) LIKE '%LL%'
UNION
SELECT DISTINCT APELLIDO2 "APELLIDOS" FROM PROFESORES WHERE UPPER(APELLIDO2) LIKE '%LL%'
;

--EJERCICIO 20
SELECT DISTINCT REPLACE(APELLIDO1,'ll','y') "APELLIDOS" FROM ALUMNOS WHERE UPPER(APELLIDO1) LIKE '%LL%'
UNION
SELECT DISTINCT REPLACE(APELLIDO2,'ll','y') "APELLIDOS" FROM ALUMNOS WHERE UPPER(APELLIDO2) LIKE '%LL%'
UNION
SELECT DISTINCT REPLACE(APELLIDO1,'ll','y') "APELLIDOS" FROM PROFESORES WHERE UPPER(APELLIDO1) LIKE '%LL%'
UNION
SELECT DISTINCT REPLACE(APELLIDO2,'ll','y') "APELLIDOS" FROM PROFESORES WHERE UPPER(APELLIDO2) LIKE '%LL%'
;

--EJERCICIO 21
SELECT A.NOMBRE,P.ID FROM ASIGNATURAS A LEFT OUTER JOIN IMPARTIR I ON A.CODIGO=I.ASIGNATURA LEFT OUTER JOIN PROFESORES P ON I.PROFESOR=P.ID
WHERE A.CREDITOS!=(NVL(A.PRACTICOS,0)+NVL(A.TEORICOS,0));

--EJERCICIO 22
SELECT DISTINCT P1.NOMBRE "NOMBREP1",P1.APELLIDO1 "APELLIDO1P1",P1.APELLIDO2 "APELLIDO2P1"
,P2.NOMBRE "NOMBREP2",P2.APELLIDO1 "APELLIDO1P2",P2.APELLIDO2 "APELLIDO2P2"
FROM PROFESORES P1 LEFT OUTER JOIN PROFESORES P2 ON P1.DIRECTOR_TESIS=P2.ID
ORDER BY P1.APELLIDO1,P1.APELLIDO2,P1.NOMBRE;

--EJERCICIO 23
SELECT 'El director de '||P1.NOMBRE||' '||P1.APELLIDO1||' '||P1.APELLIDO2||
' es '||P2.NOMBRE||' '||P2.APELLIDO1||' '||P2.APELLIDO2 "TESIS", NVL(I.TRAMOS,0) "TRAMOS"
FROM PROFESORES P1 JOIN PROFESORES P2 ON P1.DIRECTOR_TESIS=P2.ID 
LEFT OUTER JOIN INVESTIGADORES I ON P2.ID=I.ID_PROFESOR;

--EJERCICIO 24
SELECT A1.NOMBRE ,A1.APELLIDO1 ,A1.APELLIDO2,A2.NOMBRE ,A2.APELLIDO1 ,A2.APELLIDO2 
FROM ALUMNOS A1 LEFT OUTER JOIN ALUMNOS A2 ON A1.FECHA_PRIM_MATRICULA=A2.FECHA_PRIM_MATRICULA AND A1.DNI!=A2.DNI
ORDER BY A1.APELLIDO1,A1.APELLIDO2,A1.NOMBRE;

--EJERCICIO 25
SELECT ASI.NOMBRE "ASIGNATURA", ASI.CURSO, I.GRUPO, P.NOMBRE, P.APELLIDO1
FROM ASIGNATURAS ASI FULL OUTER JOIN IMPARTIR I ON ASI.CODIGO=I.ASIGNATURA
LEFT OUTER JOIN PROFESORES P ON I.PROFESOR=P.ID
ORDER BY ASI.CODIGO;

--EJERCICIO 26
SELECT NOMBRE, ID FROM PROFESORES
WHERE ID NOT IN (SELECT PROFESOR FROM IMPARTIR );

--EJERCICIO 27
SELECT NOMBRE,APELLIDO1,APELLIDO2 FROM ALUMNOS WHERE GENERO='FEM' AND
DNI IN (SELECT ALUMNO FROM MATRICULAR WHERE ASIGNATURA='115') AND ROWNUM <=2;

--EJERCICIO 28
SELECT * FROM PROFESORES WHERE ID NOT IN (SELECT DISTINCT DIRECTOR_TESIS FROM PROFESORES WHERE DIRECTOR_TESIS IS NOT NULL);

--EJERCICIO 29
SELECT NOMBRE, CODIGO FROM ASIGNATURAS WHERE CODIGO IN(
SELECT DISTINCT A1.CODIGO FROM ASIGNATURAS A1, ASIGNATURAS A2 WHERE NVL(A1.CURSO,0)=NVL(A2.CURSO,0) AND NVL(A1.CREDITOS,0)<NVL(A2.CREDITOS,0)); 
SELECT A1.NOMBRE, A1.CODIGO FROM ASIGNATURAS A1 WHERE EXISTS(
SELECT DISTINCT A1.* FROM ASIGNATURAS A2 WHERE NVL(A1.CURSO,0)=NVL(A2.CURSO,0) AND NVL(A1.CREDITOS,0)<NVL(A2.CREDITOS,0));

--EJERCICIO 30
SELECT NOMBRE, CODIGO FROM ASIGNATURAS WHERE CODIGO NOT IN(
SELECT DISTINCT A1.CODIGO FROM ASIGNATURAS A1, ASIGNATURAS A2 WHERE NVL(A1.CURSO,0)=NVL(A2.CURSO,0) AND NVL(A1.CREDITOS,0)<NVL(A2.CREDITOS,0)); 
SELECT A1.NOMBRE, A1.CODIGO FROM ASIGNATURAS A1 WHERE NOT EXISTS(
SELECT DISTINCT A1.* FROM ASIGNATURAS A2 WHERE NVL(A1.CURSO,0)=NVL(A2.CURSO,0) AND NVL(A1.CREDITOS,0)<NVL(A2.CREDITOS,0));
